### ISSUE TITLE
Node 18 LTS not allowed on backend

### ISSUE THREAD

**Issue by kleenkanteen** [octree-gva/caroster#16]
In the backend folder, package.json, the node versions are `"node": ">=12.x.x <=16.x.x"`. I have node 18 LTS installed so I error upon running `yarn`.

I did the following to the backend's package.json and was able to make everything work:
Had to change line 36 to `"strapi-plugin-init-admin-user": "^v0.2.1"`
Changed line 45 to `"node": ">=16.x.x"`

Ok to make a PR to update these 2 lines?

**Comment by 5ika** [comment]
This line was configured for compatibility with an older version of Strapi. Since we've updated Strapi to v4.6, you can update this line without problem for Node 18 in a PR (thanks).
We will update Strapi and other dependencies soon.
