### ISSUE TITLE
Not detecting english language

### ISSUE THREAD

**Issue by kleenkanteen** [octree-gva/caroster#22]
I tried on brave, edge, chrome, and firefox. In all browsers it defaults to french instead of english. Some examples:

![image](https://github.com/octree-gva/caroster/assets/67878058/0613d24a-26f3-4e2f-8b7b-19e37c39681a)

![image](https://github.com/octree-gva/caroster/assets/67878058/a396face-608d-4158-8be3-143ba1ef8c98)

I remember seeing some code where nextjs detects the browser's language and changes the locale based on that. It is not working though. Ok to make a PR to fix it?

**Comment by 5ika** [comment]
caroster.io is a different website, detached from the app in this repo. It uses Squarespace with limited possibilities so we can't do better than this for now, sorry :-/

App is hosted on app.caroster.io.

**Comment by kleenkanteen** [comment]
@5ika Possible to have the default language on Squarespace be english?

**Comment by Xavierova** [comment]
Hi @kleenkanteen,

Thank you for your feedback, unfortunately we will be able to fix the website soon. But it is planned to have a smarter version that can recognize language.

In the meantime, it is better to share the website to then EN url : https://caroster.io/en/home
